# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151014033929 on 2015-10-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20151024_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='no_of_posts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='no_of_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='no_of_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
