# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151014033929 on 2015-10-24 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20151024_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
