# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151014033929 on 2015-10-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
